# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: 'https://github.com/gruntwork-io/pre-commit'
  rev: v0.1.17
  hooks:
  - id: 'shellcheck'
    #args: ["--enable require-variable-braces,deprecate-which"]
- repo: https://github.com/psf/black
  rev: 22.3.0 #stable 0
  hooks:
  - id: black
  language_version: python3
- repo: https://github.com/mattlqx/pre-commit-ruby
  rev: v1.3.5
  hooks:
  - id: rubocop
  - id: foodcritic
  - id: cookstyle
  - id: rspec
  - id: chef-cookbook-version
